---
web_app_default_port: 5000
web_app_default_restart_policy: unless-stopped
web_app_default_environment_variables: '{}'
web_app_compose_project_dir: "/opt/{{ app_name }}"
web_app_docker_compose_version: "'3.8'"
web_app_wipe: false
