apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dinfochart.fullname" . }}
  labels:
    {{- include "dinfochart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dinfochart.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # Extra pods during update
      maxUnavailable: 0  # Ensure availability
  template:
    metadata:
      labels:
        {{- include "dinfochart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "dinfoservice-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/myapp/config"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image:  "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
          - containerPort: {{ .Values.service.port }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: app-config
              mountPath: /config
              readOnly: true
            - name: app-data
              mountPath: /data
          envFrom:
            - configMapRef:
                name: {{ include "dinfochart.fullname" . }}-env
      volumes:
        - name: app-config
          configMap:
            name: devops-info-config
        - name: app-data
          persistentVolumeClaim:
            claimName: devops-info-data
