apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "dinfochart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dinfochart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dinfochart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "dinfoservice-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/myapp/config"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image:  "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
          - containerPort: {{ .Values.service.port }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: app-config
              mountPath: /config
              readOnly: true
            - name: data-volume
              mountPath: /data
          envFrom:
            - configMapRef:
                name: {{ include "dinfochart.fullname" . }}-env
      volumes:
        - name: app-config
          configMap:
            name: {{ include "dinfochart.fullname" . }}-config
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "dinfochart.fullname" . }}-data
  strategy:
    blueGreen:
      activeService: {{ include "dinfochart.fullname" . }}
      previewService: {{ include "dinfochart.fullname" . }}-preview
      autoPromotionEnabled: false  # Manual promotion
      # autoPromotionSeconds: 30  # Or auto-promote after 30s
