- name: Install required apt packages
  tags:
    - packages
  block:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install common packages
      ansible.builtin.apt:
        name: "{{ common_packages }}"
        state: present
  rescue:
    - name: Fix apt
      ansible.builtin.apt:
        state: fixed
  always:
    - name: Log completion
      ansible.builtin.file:
        path: /tmp/ansible-packages-complete
        state: touch
        mode: '644'

- name: Set timezone to UTC
  community.general.timezone:
    name: Etc/UTC
    hwclock: UTC
