apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-infoservice
  labels:
    app: devops-infoservice
spec:
  replicas: 5
  selector:
    matchLabels:
      app: devops-infoservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # Extra pods during update
      maxUnavailable: 0  # Ensure availability
  template:
    metadata:
      labels:
        app: devops-infoservice
    spec:
      containers:
      - name: devops-infoservice
        image: 127.0.0.1:5000/timurusmanov/devops-infoservice:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
