---
- name: restart container
  community.docker.docker_container:
    name: '{{ app_container_name }}'
    image: '{{ docker_image }}:{{ docker_image_tag }}'
    published_ports:
      - '{{ app_port }}:{{ default_port }}'
    env: "{{ default_environment_variables }}"
    restart_policy: '{{ default_restart_policy }}'
    state: restarted
